name: Publish Gradle Plugin

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Check README
        run: |
          if grep -q "id(\"io.github.klahap.mccgen\") version \"$GITHUB_REF_NAME\"" README.md; then
            echo "README is valid"
          else
            echo "Error, update plugin version in README.md"
            exit 1
          fi
      - name: publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins
